
TEST_SRCS := $(wildcard $(TEST_DIR)/test_*.c)
TEST_TARGETS := $(patsubst $(TEST_DIR)/test_%.c,test_%, $(TEST_SRCS))

.PHONY: test

test: $(TEST_TARGETS)
	@echo "All tests passed!"

# Run target for each test source: depends on the built executable then runs it
test_%: $(TEST_DIR)/test_%
	./$(TEST_DIR)/test_$*

$(TEST_DIR)/test_%: $(SRCS) $(TEST_DIR)/unity.c 
	$(CC_NATIVE) $(TEST_CC_FLAGS) $^  $(TEST_DIR)/test_$*.c -o $@
