name: Test CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Emscripten toolchain
      uses: mymindstorm/setup-emsdk@v14 
      with:
        version: 'latest'

    - name: Verify emcc installation
      run: emcc --version

    - name: Install Dependencies
      run: npm install

    - name: build
      run: make build

    - name: test
      run: make test
